In [2]:
import pandas as pd
import csv

**Note**: As the workflow was not set to the current settings, this analysis was later re-done on the consolidation file, after the column "chair" was added to 
allow for the analysis of the IAA for non-procedural speeches.

In [3]:
df = pd.read_excel("Test1_consolidation.xlsx")

In [4]:
#df

# 6-level schema analysis (Cohen's Kappa (κ))

In [5]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['tamara_tag']
annotator2 = df['katja_tag']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.8311111111111111)

# AAI for only non-procedural speeches

In [6]:
df_non = df[df['chair'] != True]
df_non

,ID,text,tamara_tag,katja_tag,tamara_comments,katja_comments,tamara_flagged,katja_flagged,chair,final_tag
0,ParlaMint-SI_2004-03-23-SDZ3-Redna-35.u243,"Gospod predsednik, ker je bil k predlogu zakon...",P_Neutral,P_Neutral,"No actual sentiment, purely a neutral request ...","Procedural, very neutral.",NaN,NaN,NaN,P_Neutral
1,ParlaMint-SI_2004-04-09-SDZ3-Izredna-42.u44,"Hvala, gospod predsedujoči. Ta amandma, ki smo...",Negative,M_Negative,A hard one. This one definitly couldn't fall u...,The amandment is not sufficiently dealing with...,1.0,NaN,NaN,Negative
2,ParlaMint-SI_2004-03-24-SDZ3-Redna-35.u165,"Hvala. Še enkrat sem se oglasil, čeprav sem mi...",Negative,Negative,"Clear disagreement with the previous speaker, ...",While there are several passages in the speech...,NaN,NaN,NaN,Negative
3,ParlaMint-SI_2004-03-25-SDZ3-Redna-35.u167,Spoštovane kolegice in kolegi. Ko obravnavamo ...,Negative,Negative,Although at first it seemed like it would be a...,"TLDR: I agree to some aspects, but if we do th...",NaN,1.0,NaN,Negative
7,ParlaMint-SI_2004-04-08-SDZ3-Izredna-42.u168,Hvala za besedo. Ta amandma k 102. členu je ze...,Negative,Negative,Clear opposition and negative sentiment.,"Very very very clear speakers position, using ...",NaN,NaN,NaN,Negative
8,ParlaMint-SI_2004-05-12-SDZ3-Izredna-45.u20,"Gospod predsednik, kolegice in kolegi! Ministe...",M_Negative,Positive,"First part positive, encouraging, second part ...","Very statement, much positive. Either P_Neutra...",NaN,NaN,NaN,M_Positive
9,ParlaMint-SI_2004-11-17-SDZ4-Izredna-02.u138,"Hvala, predsednik. Hvaležen sem predhodniku, k...",M_Negative,M_Negative,"First part positive, agreement, support, secon...",Short and positive support to the decree but t...,NaN,1.0,NaN,M_Negative
10,ParlaMint-SI_2004-04-21-SDZ3-Izredna-43.u183,"Hvala lepa, gospa podpredsednica. Predstavniki...",Positive,Positive,Could also be P_Neutral.,"Starts with very statement-like structure, but...",NaN,NaN,NaN,Positive
12,ParlaMint-SI_2004-03-26-SDZ3-Redna-35.u52,"Minister je govoril, da se določa samo posebno...",Negative,Negative,Clearly expressed opinion.,Direct and clear negative opinion on the subject.,NaN,NaN,NaN,Negative
18,ParlaMint-SI_2004-08-31-SDZ3-Izredna-50.u123,Hvala za besedo. Ne bom nadaljeval s pokojnina...,Negative,Negative,"Clearly expressed opinion, with negative senti...",NaN,NaN,NaN,NaN,Negative

In [7]:
annotator_non_1 = df_non['tamara_tag']
annotator_non_2 = df_non['katja_tag']
cohen_kappa_score(annotator_non_1, annotator_non_2)

np.float64(0.6825396825396826)

# 3-level analysis (Cohen's Kappa (κ))

In [8]:
df.loc[(df['tamara_tag'] == 'Negative') | (df['tamara_tag'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df.loc[(df['tamara_tag'] == 'Positive') | (df['tamara_tag'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df.loc[(df['tamara_tag'] == 'P_Neutral') | (df['tamara_tag'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

In [9]:
df.loc[(df['katja_tag'] == 'Negative') | (df['katja_tag'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df.loc[(df['katja_tag'] == 'Positive') | (df['katja_tag'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df.loc[(df['katja_tag'] == 'P_Neutral') | (df['katja_tag'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

In [10]:
annotator1 = df['sent_tamara']
annotator2 = df['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.9064039408866995)

# 3-level analysis (Kappa, non-procedural only)

In [11]:
df_non.loc[(df_non['tamara_tag'] == 'Negative') | (df_non['tamara_tag'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df_non.loc[(df_non['tamara_tag'] == 'Positive') | (df_non['tamara_tag'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df_non.loc[(df_non['tamara_tag'] == 'P_Neutral') | (df_non['tamara_tag'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_1973/525028615.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tamara_tag'] == 'Negative') | (df_non['tamara_tag'] == 'M_Negative'), 'sent_tamara'] = 'Negative'

In [12]:
df_non.loc[(df_non['katja_tag'] == 'Negative') | (df_non['katja_tag'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df_non.loc[(df_non['katja_tag'] == 'Positive') | (df_non['katja_tag'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df_non.loc[(df_non['katja_tag'] == 'P_Neutral') | (df_non['katja_tag'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_1973/3640135515.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['katja_tag'] == 'Negative') | (df_non['katja_tag'] == 'M_Negative'), 'sent_katja'] = 'Negative'

In [13]:
#df_non

In [14]:
annotator1 = df_non['sent_tamara']
annotator2 = df_non['sent_tamara']
cohen_kappa_score(annotator1, annotator2)

np.float64(1.0)

# Generating dataset for consolidation

Adding new column for the final annotation, provided with consolidation

In [15]:
#df['final_tag'] = df.apply(lambda row: row['tamara_tag'] if row['tamara_tag'] == row['katja_tag'] else None, axis=1)

In [16]:
#df.to_csv("Test1_consolidation.csv", encoding = 'utf-8')

# Kappa scores aggregation 
Aggregation of the scores to a new df

In [17]:
kappa_scores = {
    "6-level":{
        "full":0.83,
        "non-procedural":0.68
        
    },
    "3-level":{
        "full": 0.90,
        "non-procedural":1.0
    }
}

df_kappa = pd.DataFrame(kappa_scores)

In [18]:
def create_test_df(kappa_scores, test_label):
    df_kappa = pd.DataFrame(kappa_scores).reset_index()
    df_kappa.rename(columns={'index': 'Type'}, inplace=True)
    df_kappa['Phase'] = test_label
    # Reorder columns to place 'Test' before 'Type'
    df_kappa = df_kappa[['Phase', 'Type', '6-level', '3-level']]
    return df_kappa

In [19]:
df_test1 = create_test_df(kappa_scores, 'Test1')
df_test1

   Phase            Type  6-level  3-level
0  Test1            full     0.83      0.9
1  Test1  non-procedural     0.68      1.0

In [20]:
df_test1.to_csv("Kappa_scores_test1.csv", index=False)