In [1]:
import pandas as pd
import csv

In [2]:
df = pd.read_csv("Main5_combined.csv", delimiter = ',', encoding='utf-8')

In [3]:
df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2010-04-22-SDZ5-Redna-16.u265,"Hvala lepa. Besedo ima gospod Jožef Jerovšek, ...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
1,ParlaMint-SI_2003-05-28-SDZ3-Redna-26.u129,"Poglejte, v vaši obrazložitvi okoli 26. člena,...",M_Positive,Negative,"A bit loaded at first, but relises his mistake.",Sarcastic and negative,NaN,NaN,False,NaN
2,ParlaMint-SI_2019-11-21-SDZ8-Redna-13.u243,"Hvala lepa, predsedujoči, za besedo. Jaz bi že...",Positive,Positive,Support.,NaN,NaN,NaN,False,NaN
3,ParlaMint-SI_2016-10-18-SDZ7-Redna-23.u99,"Hvala lepa. Predlagateljica gospa Jelka Godec,...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
4,ParlaMint-SI_2014-12-04-SDZ7-Izredna-07.u72,Hvala lepa. Gospod Jožef Horvat bo predstavil ...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN

# 6-level schema analysis (Cohen's Kappa (κ))

In [4]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['tag_tamara']
annotator2 = df['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.748190116462071)

# κ for non-procedural and procedural speech

In [5]:
df_non = df[df['chair'] != True]

In [6]:
df_procedural = df[df['chair'] == True]

In [85]:
#df_procedural

In [7]:
annotator1 = df_non['tag_tamara']
annotator2 = df_non['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.6138211382113821)

In [8]:
annotator1_procedural = df_procedural['tag_tamara']
annotator2_procedural = df_procedural['tag_katja']
cohen_kappa_score(annotator1_procedural, annotator2_procedural)

np.float64(0.7285652735889703)

# 3-level analysis (Cohen's Kappa (κ))

In [9]:
df.loc[(df['tag_tamara'] == 'Negative') | (df['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df.loc[(df['tag_tamara'] == 'Positive') | (df['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df.loc[(df['tag_tamara'] == 'P_Neutral') | (df['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

In [10]:
df.loc[(df['tag_katja'] == 'Negative') | (df['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df.loc[(df['tag_katja'] == 'Positive') | (df['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df.loc[(df['tag_katja'] == 'P_Neutral') | (df['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

In [90]:
#df

In [11]:
annotator1 = df['sent_tamara']
annotator2 = df['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.8772948227854075)

In [12]:
df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df_non.loc[(df_non['tag_tamara'] == 'Positive') | (df_non['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df_non.loc[(df_non['tag_tamara'] == 'P_Neutral') | (df_non['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_1492/136232902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'

In [13]:
df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df_non.loc[(df_non['tag_katja'] == 'Positive') | (df_non['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df_non.loc[(df_non['tag_katja'] == 'P_Neutral') | (df_non['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

/var/folders/l_/t5l44v1s7d9168_x8bm5ly0h0000gn/T/ipykernel_1492/4240778448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'

In [14]:
annotator1 = df_non['sent_tamara']
annotator2 = df_non['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.7926669576604103)

# Agreement rates

## 6-level full

In [15]:
df['agreement_tag'] = df['tag_tamara'] == df['tag_katja']
df['agreement_sent'] = df['sent_tamara'] == df['sent_katja']
agreement_tag = df[df['agreement_tag'] == True]
(len(agreement_tag) / len(df)) * 100

84.0

## 6-level non-procedural

In [16]:
df2 = df[df['chair'] == False]
agreement_tag_non = df2[df2['agreement_tag'] == True]
(len(agreement_tag_non) / len(df2)) * 100

72.63157894736842

## 3-level full

In [17]:
agreement_sent = df[df['agreement_sent'] == True]
(len(agreement_sent) / len(df)) * 100

93.5

In [18]:
agreement_sent_non = df2[df2['agreement_sent'] == True]
(len(agreement_sent_non) / len(df2)) * 100

89.47368421052632

# Generating dataset for consolidation

Adding new column for the final annotation, provided with consolidation

Note: Comment out after consolidation dataset is created

In [20]:
df['final_tag'] = df.apply(lambda row: row['tag_tamara'] if row['tag_tamara'] == row['tag_katja'] else None, axis=1)
df.to_csv("Main5_consolidation.csv", encoding = 'utf-8')

# Aggergating Kappa scores

In [21]:
kappa_scores = {
    "6-level":{
        "full":0.75,
        "non-procedural":0.61
        
    },
    "3-level":{
        "full": 0.88,
        "non-procedural":0.79
    }
}

df_kappa = pd.DataFrame(kappa_scores)

def create_test_df(kappa_scores, test_label):
    df_kappa = pd.DataFrame(kappa_scores).reset_index()
    df_kappa.rename(columns={'index': 'Type'}, inplace=True)
    df_kappa['Phase'] = test_label
    # Reorder columns to place 'Test' before 'Type'
    df_kappa = df_kappa[['Phase', 'Type', '6-level', '3-level']]
    return df_kappa

In [22]:
df_test = create_test_df(kappa_scores, 'Main5')
df_test

   Phase            Type  6-level  3-level
0  Main5            full     0.75     0.88
1  Main5  non-procedural     0.61     0.79

In [23]:
df_test.to_csv("../Kappa_scores_Main5.csv", index=False)