In [19]:
import csv
import random
import pandas as pd
import numpy as np

## Sampling main annotation subsets
To avoid duplicates between the tests and the main annotation dataset, the main annotation dataset was resampled by sampling every 309th utterance (in the notebook Sampling_tests.ipynb) to better match the corpus distribution. The order of the utterances was then randomised. This is later used to generate the dev and train split used to test the sentiment score aggregation methods.

For the main annotation (which was split into 5 parts), each main annotation sample comprises 200 utterances to be annotated.

In [20]:
df = pd.read_csv("../Datasets/Sample.csv")
df.head()

,ID,Text,Annotation,Comments,Flag,Chair
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,"Ni replike na repliko. Gospa ministrica, potem...",NaN,NaN,NaN,True
1,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,NaN,NaN,NaN,True
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,"Hvala lepa. V bistvu se strinjam z vami, gospo...",NaN,NaN,NaN,False
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,"Hvala, podpredsednik. Hvala tudi za vprašanje,...",NaN,NaN,NaN,False
4,ParlaMint-SI_2009-11-18-SDZ5-Redna-11.u120,Besedo ima gospod Silven Majhenič.,NaN,NaN,NaN,True

## Checking the distribution of speech types (procedural/non-procedural)
The dataset is relatively balanced with respect to the classification of speech types.
Procedural speech comprises approximately 52% of the dataset, while non-procedural speech constitutes around 48%.

In [21]:
df_procedural = df[df['Chair'] == True]
no_of_procedural = len(df_procedural)
distribution = (no_of_procedural / 1000) * 100
distribution

52.0

## Main 1 annotation sample

In [22]:
df1 = df.iloc[:200, :].copy()
df1.head()

,ID,Text,Annotation,Comments,Flag,Chair
0,ParlaMint-SI_2010-09-07-SDZ5-Izredna-28.u90,"Ni replike na repliko. Gospa ministrica, potem...",NaN,NaN,NaN,True
1,ParlaMint-SI_2011-06-16-SDZ5-Redna-29.u107,Hvala lepa. Besedo ima Silva Črnugelj. Priprav...,NaN,NaN,NaN,True
2,ParlaMint-SI_2011-06-21-SDZ5-Redna-29.u178,"Hvala lepa. V bistvu se strinjam z vami, gospo...",NaN,NaN,NaN,False
3,ParlaMint-SI_2020-09-21-SDZ8-Redna-20.u276,"Hvala, podpredsednik. Hvala tudi za vprašanje,...",NaN,NaN,NaN,False
4,ParlaMint-SI_2009-11-18-SDZ5-Redna-11.u120,Besedo ima gospod Silven Majhenič.,NaN,NaN,NaN,True

In [23]:
df1_procedural = df1[df1['Chair'] == True]
len(df1_procedural)

101

In [24]:
df1.to_csv("../Datasets/Main1_sample.csv", index=False)
df1.to_excel("../Datasets/Main1_sample.xlsx", index=False)

## Main 2 annotation sample

In [25]:
df2 = df.iloc[200:400, :].copy()
df2

,ID,Text,Annotation,Comments,Flag,Chair
200,ParlaMint-SI_2013-10-21-SDZ6-Redna-18.u63,Hvala. Besedo dajem gospodu Samu Omerzelu.,NaN,NaN,NaN,True
201,ParlaMint-SI_2010-12-23-SDZ5-Izredna-36.u69,Hvala lepa. Končali smo s predstavitvijo stali...,NaN,NaN,NaN,True
202,ParlaMint-SI_2020-10-15-SDZ8-Izredna-46.u33,"Glejte, gospa [[…]] [[oglašanje iz dvorane]]",NaN,NaN,NaN,True
203,ParlaMint-SI_2010-11-17-SDZ5-Redna-22.u106,"Hvala lepa. Glasujemo. Prekinjam. Prosim, gosp...",NaN,NaN,NaN,True
204,ParlaMint-SI_2005-10-26-SDZ4-Redna-10.u151,Hvala lepa. In še kot zadnjega vabim k besedi ...,NaN,NaN,NaN,True
...,...,...,...,...,...,...
395,ParlaMint-SI_2014-01-30-SDZ6-Redna-21.u62,"Spoštovana podpredsednica, spoštovani predstav...",NaN,NaN,NaN,False
396,ParlaMint-SI_2009-11-24-SDZ5-Redna-11.u35,Spoštovani predsedujoči [[...]],NaN,NaN,NaN,False
397,ParlaMint-SI_2009-05-21-SDZ5-Redna-06.u181,Hvala lepa. Besedo ima Miro Petek. Prosim.,NaN,NaN,NaN,True
398,ParlaMint-SI_2011-07-12-SDZ5-Izredna-43.u28,"Hvala za besedo. Mislim, da je rojstvo vsake d...",NaN,NaN,NaN,False
399,ParlaMint-SI_2004-06-23-SDZ3-Izredna-47.u39,Hvala. K besedi vabim kolegico Irmo Pavlinič K...,NaN,NaN,NaN,True

In [26]:
df2_procedural = df2[df2['Chair'] == True]
len(df2_procedural)

108

In [27]:
df2.to_csv("../Datasets/Main2_sample.csv", index=False)
df2.to_excel("../Datasets/Main2_sample.xlsx", index=False)

## Main 3 annotation sample

In [28]:
df3 = df.iloc[400:600, :].copy()
df3.head()

,ID,Text,Annotation,Comments,Flag,Chair
400,ParlaMint-SI_2013-03-04-SDZ6-Redna-11.u10,"Spoštovani predsednik Vlade, spoštovana minist...",NaN,NaN,NaN,False
401,ParlaMint-SI_2017-03-21-SDZ7-Redna-28.u162,Dragi poslanke in poslanci! Danes ne bomo govo...,NaN,NaN,NaN,False
402,ParlaMint-SI_2010-11-16-SDZ5-Izredna-33.u1,Spoštovane kolegice poslanke in kolegi poslanc...,NaN,NaN,NaN,True
403,ParlaMint-SI_2010-01-28-SDZ5-Redna-13.u172,"Hvala lepa za besedo, gospod podpredsednik. Sp...",NaN,NaN,NaN,False
404,ParlaMint-SI_2021-09-21-SDZ8-Redna-25.u92,"Hvala za besedo, gospa podpredsednica. Gospe p...",NaN,NaN,NaN,False

In [29]:
df3_procedural = df3[df3['Chair'] == True]
len(df3_procedural)

103

In [30]:
df3.to_csv("../Datasets/Main3_sample.csv", index=False)
df3.to_excel("../Datasets/Main3_sample.xlsx", index=False)

## Main 4 annotation sample

In [31]:
df4 = df.iloc[600:800, :].copy()
df4.head()

,ID,Text,Annotation,Comments,Flag,Chair
600,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u93,"Hvala lepa tudi vam. Gospod Mihael Prevc, nasl...",NaN,NaN,NaN,True
601,ParlaMint-SI_2015-01-26-SDZ7-Redna-04.u152,"Hvala lepa za besedo. Spoštovane ministrice, m...",NaN,NaN,NaN,False
602,ParlaMint-SI_2006-11-29-SDZ4-Redna-22.u165,"Kolega Slavko Gaber, v temu trenutku vam lahko...",NaN,NaN,NaN,True
603,ParlaMint-SI_2001-03-01-SDZ3-Redna-03.u116,"Moram replicirati. Kolega Moge - ne moram, amp...",NaN,NaN,NaN,False
604,ParlaMint-SI_2021-12-16-SDZ8-Redna-28.u22,"Hvala za besedo, podpredsednica. Lep pozdrav v...",NaN,NaN,NaN,False

In [32]:
df4_procedural = df4[df4['Chair'] == True]
len(df4_procedural)

103

In [33]:
df4.to_csv("../Datasets/Main4_sample.csv", index=False)
df4.to_excel("../Datasets/Main4_sample.xlsx", index=False)

# Main 5 annotation sample

In [34]:
df5 = df.iloc[800:, :].copy()
df5.head()

,ID,Text,Annotation,Comments,Flag,Chair
800,ParlaMint-SI_2010-04-22-SDZ5-Redna-16.u265,"Hvala lepa. Besedo ima gospod Jožef Jerovšek, ...",NaN,NaN,NaN,True
801,ParlaMint-SI_2003-05-28-SDZ3-Redna-26.u129,"Poglejte, v vaši obrazložitvi okoli 26. člena,...",NaN,NaN,NaN,False
802,ParlaMint-SI_2019-11-21-SDZ8-Redna-13.u243,"Hvala lepa, predsedujoči, za besedo. Jaz bi že...",NaN,NaN,NaN,False
803,ParlaMint-SI_2016-10-18-SDZ7-Redna-23.u99,"Hvala lepa. Predlagateljica gospa Jelka Godec,...",NaN,NaN,NaN,True
804,ParlaMint-SI_2014-12-04-SDZ7-Izredna-07.u72,Hvala lepa. Gospod Jožef Horvat bo predstavil ...,NaN,NaN,NaN,True

In [35]:
df5_procedural = df5[df5['Chair'] == True]
len(df5_procedural)

105

In [36]:
df5.to_csv("../Datasets/Main5_sample.csv", index=False)
df5.to_excel("../Datasets/Main5_sample.xlsx", index=False)

# Dev and test split for sentiment aggregation

Generating the dev and test split of the new main annotation sample that will be used to develop and test method for the sentiment score aggregation.

In [38]:
from sklearn.model_selection import train_test_split
dev_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
print(f'Development set size: {len(dev_df)} rows')
print(f'Test set size: {len(test_df)} rows')

Development set size: 800 rows
Test set size: 200 rows

In [39]:
dev_df.to_csv('../Datasets/Sample_dev.csv', index=False)
test_df.to_csv('../Datasets/Sample_test.csv', index=False)