In [79]:
import pandas as pd
import csv

In [80]:
df = pd.read_csv("Main4_combined.csv", delimiter = ',', encoding='utf-8')

In [81]:
df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2013-11-22-SDZ6-Redna-19.u93,"Hvala lepa tudi vam. Gospod Mihael Prevc, nasl...",P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
1,ParlaMint-SI_2015-01-26-SDZ7-Redna-04.u152,"Hvala lepa za besedo. Spoštovane ministrice, m...",M_Negative,M_Negative,"Divided, valid questions.","First two sentences seem to be positive, howev...",NaN,1.0,False,NaN
2,ParlaMint-SI_2006-11-29-SDZ4-Redna-22.u165,"Kolega Slavko Gaber, v temu trenutku vam lahko...",P_Neutral,P_Neutral,Procedural. I guess could be N_Neutral but its...,NaN,NaN,NaN,True,NaN
3,ParlaMint-SI_2001-03-01-SDZ3-Redna-03.u116,"Moram replicirati. Kolega Moge - ne moram, amp...",M_Positive,Negative,"Clealry a defensive response, but positive.",Speaker presents arguments on why the proposal...,NaN,NaN,False,NaN
4,ParlaMint-SI_2021-12-16-SDZ8-Redna-28.u22,"Hvala za besedo, podpredsednica. Lep pozdrav v...",Positive,Positive,"Support, but also positive parts presented.",At the end there is a slight negative connotat...,NaN,NaN,False,NaN

# 6-level schema analysis (Cohen's Kappa (κ))

In [82]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['tag_tamara']
annotator2 = df['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.7373653997673808)

# κ for non-procedural and procedural speech

In [83]:
df_non = df[df['chair'] != True]

In [84]:
df_procedural = df[df['chair'] == True]

In [85]:
#df_procedural

In [86]:
annotator1 = df_non['tag_tamara']
annotator2 = df_non['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.5012853470437018)

In [87]:
annotator1_procedural = df_procedural['tag_tamara']
annotator2_procedural = df_procedural['tag_katja']
cohen_kappa_score(annotator1_procedural, annotator2_procedural)

np.float64(0.8453453453453453)

# 3-level analysis (Cohen's Kappa (κ))

In [88]:
df.loc[(df['tag_tamara'] == 'Negative') | (df['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df.loc[(df['tag_tamara'] == 'Positive') | (df['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df.loc[(df['tag_tamara'] == 'P_Neutral') | (df['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

In [89]:
df.loc[(df['tag_katja'] == 'Negative') | (df['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df.loc[(df['tag_katja'] == 'Positive') | (df['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df.loc[(df['tag_katja'] == 'P_Neutral') | (df['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

In [90]:
#df

In [91]:
annotator1 = df['sent_tamara']
annotator2 = df['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.8340466416280898)

In [92]:
df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df_non.loc[(df_non['tag_tamara'] == 'Positive') | (df_non['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df_non.loc[(df_non['tag_tamara'] == 'P_Neutral') | (df_non['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_96055/136232902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'

In [93]:
df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df_non.loc[(df_non['tag_katja'] == 'Positive') | (df_non['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df_non.loc[(df_non['tag_katja'] == 'P_Neutral') | (df_non['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_96055/4240778448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'

In [94]:
annotator1 = df_non['sent_tamara']
annotator2 = df_non['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.619870908252651)

# Agreement rates

## 6-level full

In [95]:
df['agreement_tag'] = df['tag_tamara'] == df['tag_katja']
df['agreement_sent'] = df['sent_tamara'] == df['sent_katja']
agreement_tag = df[df['agreement_tag'] == True]
(len(agreement_tag) / len(df)) * 100

82.5

## 6-level non-procedural

In [107]:
df2 = df[df['chair'] == False]
agreement_tag_non = df2[df2['agreement_tag'] == True]
(len(agreement_tag_non) / len(df2)) * 100

67.0103092783505

## 3-level full

In [109]:
agreement_sent = df[df['agreement_sent'] == True]
(len(agreement_sent) / len(df)) * 100

90.5

In [111]:
agreement_sent_non = df2[df2['agreement_sent'] == True]
(len(agreement_sent_non) / len(df2)) * 100

82.4742268041237

# Generating dataset for consolidation

Adding new column for the final annotation, provided with consolidation

Note: Comment out after consolidation dataset is created

In [99]:
#df['final_tag'] = df.apply(lambda row: row['tag_tamara'] if row['tag_tamara'] == row['tag_katja'] else None, axis=1)
#df.to_csv("Main4_consolidation.csv", encoding = 'utf-8')

# Aggergating Kappa scores

In [122]:
kappa_scores = {
    "6-level":{
        "full":0.73,
        "non-procedural":0.50
        
    },
    "3-level":{
        "full": 0.83,
        "non-procedural":0.62
    }
}

df_kappa = pd.DataFrame(kappa_scores)

def create_test_df(kappa_scores, test_label):
    df_kappa = pd.DataFrame(kappa_scores).reset_index()
    df_kappa.rename(columns={'index': 'Type'}, inplace=True)
    df_kappa['Phase'] = test_label
    # Reorder columns to place 'Test' before 'Type'
    df_kappa = df_kappa[['Phase', 'Type', '6-level', '3-level']]
    return df_kappa

In [124]:
df_test = create_test_df(kappa_scores, 'Main4')
df_test

   Phase            Type  6-level  3-level
0  Main4            full     0.73     0.83
1  Main4  non-procedural     0.50     0.62

In [102]:
df_test.to_csv("../Kappa_scores_Main4.csv", index=False)