In [17]:
import pandas as pd
import csv

sentiment = pd.read_csv("pilot3.csv", delimiter=";")
sentiment.head()

,id,text,timestamp_tamara,flagged_tamara,comment_tamara,tag_tamara,timestamp_anze,flagged_anze,comment_anze,tag_anze,timestamp_katja,flagged_katja,comment_katja,tag_katja,rev_tamara,rev_anze,rev_katja,final_tag
0,101,"Govorimo samo o višjih davkih, ki je najlažja ...",2023/03/02 13:08:30,NaN,"Maybe not the strongest, but opinion is heavil...",Negative,2023/03/02 13:09:12,NaN,First part is for me more negativ because of t...,M_Negative,2023/03/02 13:09:14,NaN,NaN,Negative,NaN,NaN,NaN,NaN
1,102,"Popolnoma vseeno mu je, če njegov kolega propa...",2023/03/02 13:08:50,NaN,Maybe some sarcasm.,Negative,2023/03/02 13:09:40,NaN,NaN,Negative,2023/03/02 13:09:22,NaN,NaN,Negative,NaN,NaN,NaN,NaN
2,103,Z vsemi nadaljnjimi političnimi improvizacijam...,2023/03/02 13:09:42,NaN,"Opinion is not directly stated, but it is impl...",Negative,2023/03/02 13:09:54,NaN,NaN,Negative,2023/03/02 13:10:11,NaN,Statement but implied negaitve sentiment /opin...,Negative,NaN,NaN,NaN,NaN
3,104,"Še tisto malo, kar je ostalo od Slovenije od l...",2023/03/02 13:09:53,NaN,NaN,Negative,2023/03/02 13:10:11,NaN,NaN,Negative,2023/03/02 13:10:20,NaN,NaN,Negative,NaN,NaN,NaN,NaN
4,105,Grafično privlačna embalaža namreč spodbuja ne...,2023/03/02 13:11:26,True,This is a hard one. The statement itself is no...,N_Neutral,2023/03/02 13:12:57,NaN,Speaker is talkig about unpopular or negativ t...,M_Negative,2023/03/02 13:10:53,NaN,"Statement with impled negative consequences, b...",N_Neutral,NaN,NaN,NaN,NaN

In [18]:
df = sentiment.drop(['timestamp_tamara', 'timestamp_anze', 'timestamp_katja', 'rev_tamara', 'rev_anze', 'rev_katja', 'final_tag'], axis = 1)
df.head()

,id,text,flagged_tamara,comment_tamara,tag_tamara,flagged_anze,comment_anze,tag_anze,flagged_katja,comment_katja,tag_katja
0,101,"Govorimo samo o višjih davkih, ki je najlažja ...",NaN,"Maybe not the strongest, but opinion is heavil...",Negative,NaN,First part is for me more negativ because of t...,M_Negative,NaN,NaN,Negative
1,102,"Popolnoma vseeno mu je, če njegov kolega propa...",NaN,Maybe some sarcasm.,Negative,NaN,NaN,Negative,NaN,NaN,Negative
2,103,Z vsemi nadaljnjimi političnimi improvizacijam...,NaN,"Opinion is not directly stated, but it is impl...",Negative,NaN,NaN,Negative,NaN,Statement but implied negaitve sentiment /opin...,Negative
3,104,"Še tisto malo, kar je ostalo od Slovenije od l...",NaN,NaN,Negative,NaN,NaN,Negative,NaN,NaN,Negative
4,105,Grafično privlačna embalaža namreč spodbuja ne...,True,This is a hard one. The statement itself is no...,N_Neutral,NaN,Speaker is talkig about unpopular or negativ t...,M_Negative,NaN,"Statement with impled negative consequences, b...",N_Neutral

In [19]:
df.loc[df['tag_tamara'] == 'N_Neutral', 'sent_tamara'] = 'Neutral'
df.loc[df['tag_tamara'] == 'P_Neutral', 'sent_tamara'] = 'Neutral'
df.loc[df['tag_tamara'] == 'M_Negative', 'sent_tamara'] = 'Negative'
df.loc[df['tag_tamara'] == 'M_Positive', 'sent_tamara'] = 'Positive'
df.loc[df['tag_tamara'] == 'Negative', 'sent_tamara'] = 'Negative'
df.loc[df['tag_tamara'] == 'Positive', 'sent_tamara'] = 'Positive'

In [20]:
df.loc[df['tag_katja'] == 'N_Neutral', 'sent_katja'] = 'Neutral'
df.loc[df['tag_katja'] == 'P_Neutral', 'sent_katja'] = 'Neutral'
df.loc[df['tag_katja'] == 'M_Negative', 'sent_katja'] = 'Negative'
df.loc[df['tag_katja'] == 'M_Positive', 'sent_katja'] = 'Positive'
df.loc[df['tag_katja'] == 'Negative', 'sent_katja'] = 'Negative'
df.loc[df['tag_katja'] == 'Positive', 'sent_katja'] = 'Positive'

In [21]:
df.loc[df['tag_anze'] == 'N_Neutral', 'sent_anze'] = 'Neutral'
df.loc[df['tag_anze'] == 'P_Neutral', 'sent_anze'] = 'Neutral'
df.loc[df['tag_anze'] == 'M_Negative', 'sent_anze'] = 'Negative'
df.loc[df['tag_anze'] == 'M_Positive', 'sent_anze'] = 'Positive'
df.loc[df['tag_anze'] == 'Negative', 'sent_anze'] = 'Negative'
df.loc[df['tag_anze'] == 'Positive', 'sent_anze'] = 'Positive'

In [22]:
df

,id,text,flagged_tamara,comment_tamara,tag_tamara,flagged_anze,comment_anze,tag_anze,flagged_katja,comment_katja,tag_katja,sent_tamara,sent_katja,sent_anze
0,101,"Govorimo samo o višjih davkih, ki je najlažja ...",NaN,"Maybe not the strongest, but opinion is heavil...",Negative,NaN,First part is for me more negativ because of t...,M_Negative,NaN,NaN,Negative,Negative,Negative,Negative
1,102,"Popolnoma vseeno mu je, če njegov kolega propa...",NaN,Maybe some sarcasm.,Negative,NaN,NaN,Negative,NaN,NaN,Negative,Negative,Negative,Negative
2,103,Z vsemi nadaljnjimi političnimi improvizacijam...,NaN,"Opinion is not directly stated, but it is impl...",Negative,NaN,NaN,Negative,NaN,Statement but implied negaitve sentiment /opin...,Negative,Negative,Negative,Negative
3,104,"Še tisto malo, kar je ostalo od Slovenije od l...",NaN,NaN,Negative,NaN,NaN,Negative,NaN,NaN,Negative,Negative,Negative,Negative
4,105,Grafično privlačna embalaža namreč spodbuja ne...,True,This is a hard one. The statement itself is no...,N_Neutral,NaN,Speaker is talkig about unpopular or negativ t...,M_Negative,NaN,"Statement with impled negative consequences, b...",N_Neutral,Neutral,Neutral,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,196,"Se pravi, govorimo o komunikaciji tudi navzven...",NaN,Opinion??,P_Neutral,NaN,no spekers opinion just a statment,P_Neutral,NaN,Positive overall tone,Positive,Neutral,Positive,Neutral
96,197,"Jaz pa soglašam, da tisti, ki dobijo socialna ...",NaN,"I don'tbunderstand this at all, but opinion is...",Positive,NaN,spekers opinion which is on more positiv side,P_Neutral,NaN,Opinion expressed but very weak positive conno...,P_Neutral,Positive,Neutral,Neutral
97,198,"Povedal sem, da je nekdanji minister za inform...",NaN,"1. negative, 2. positive (this is above)",M_Positive,NaN,"Mixed message, but i would say it's is on posi...",M_Positive,NaN,"Statement, opinion of other, positive effect",P_Neutral,Positive,Neutral,Positive
98,199,"Tako si človek nehote pravzaprav ustvari vtis,...",NaN,NaN,N_Neutral,NaN,negativ argumment,N_Neutral,NaN,"Implied opinion, negative tone, maybe even sar...",N_Neutral,Neutral,Neutral,Neutral
99,200,"Niti enkrat več ne presenetite, kar je pravzap...",NaN,Sarcasm,Negative,NaN,negativ opinion,Negative,NaN,NaN,Negative,Negative,Negative,Negative

In [39]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['sent_tamara']
annotator2 = df['sent_katja']
annotator3 = df['sent_anze']
cohen_kappa_score(annotator2, annotator3)

0.3920498830865159

In [30]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['tag_tamara']
annotator2 = df['tag_katja']
annotator3 = df['tag_anze']
cohen_kappa_score(annotator2, annotator3)

0.362311296199896

In [35]:
import simpledorff
#simpledorff.calculate_krippendorffs_alpha_for_df(df,experiment_col='id',
 #                                                annotator_col='',
  #                                               class_col='')
#I need to first transform the table into the Krippendorffs format, probably numeric values and transpose to get the
# id, annotator and label column; no idea how to combine this one.