In [12]:
import pandas as pd
import csv

df = pd.read_csv("pilot4.csv", delimiter = ";")
df

,id,text,timestamp_tamara,flagged_tamara,comment_tamara,tag_tamara,timestamp_anze,flagged_anze,comment_anze,tag_anze,timestamp_katja,flagged_katja,comment_katja,tag_katja,rev_tamara,rev_anze,rev_katja,final_tag
0,201,"In to je, kot sem rekel, tisto, kar bo tudi v ...",2023/03/08 14:09:08,NaN,"Opinion is implied, positive sentiment.",Positive,2023/03/08 14:09:14,NaN,Speaker opinion. It's on positiv side because ...,P_Neutral,2023/03/08 14:08:37,NaN,"Kot sem rekel - speakers opinion, so positive",Positive,NaN,NaN,NaN,NaN
1,202,"Slednje se odraža tudi v sami vsebini, ki je p...",2023/03/08 14:10:07,NaN,"Implied opinion, negative sentiment.",Negative,2023/03/08 14:11:56,NaN,"The statment is negativ, but it's neutral beca...",N_Neutral,2023/03/08 14:08:48,NaN,NaN,N_Neutral,NaN,NaN,NaN,NaN
2,203,Krščanski demokrati smo dolžni opozoriti na po...,2023/03/08 14:12:18,NaN,"Negative theme, negative sentiment ""zavajanje,...",Negative,2023/03/08 14:15:06,NaN,Negativ statment and negativ sentiment of the ...,Negative,2023/03/08 14:11:11,NaN,We (KS) - implied speakers opinion,Negative,NaN,NaN,NaN,NaN
3,204,Prav preko vikenda je bila slovenska javnost š...,2023/03/08 14:15:07,NaN,Maybe sarcasm,N_Neutral,2023/03/08 14:16:57,NaN,The sentens is not direct opinion of the perso...,N_Neutral,2023/03/08 14:11:44,NaN,No implied speakers opinion but negative senti...,N_Neutral,NaN,NaN,NaN,NaN
4,205,"Preprosto zaradi tega, ker je že danes država ...",2023/03/08 14:16:40,True,"Although there is no specific negative words, ...",N_Neutral,2023/03/08 14:17:16,NaN,NaN,Negative,2023/03/08 14:12:39,NaN,"Statement without implied speakers opinion, wi...",P_Neutral,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,296,"Če bi bil jaz na vašem mestu, bi bil večkrat t...",2023/03/08 15:28:49,NaN,negative sentiment.,Negative,2023/03/08 15:34:04,NaN,Negativ argumment,Negative,2023/03/08 15:41:00,NaN,NaN,Negative,NaN,NaN,NaN,NaN
96,297,Dr. Rado Bohinc ima za seboj bogato bibliograf...,2023/03/08 15:29:03,NaN,positive factual statement,P_Neutral,2023/03/08 15:34:15,NaN,NaN,Positive,2023/03/08 15:41:32,NaN,NaN,P_Neutral,NaN,NaN,NaN,NaN
97,298,"S pozdravi bom pa začel pri tistih, ki jih je ...",2023/03/08 15:29:22,NaN,"a hello,positve, no opinion",P_Neutral,2023/03/08 15:34:27,NaN,NaN,Positive,2023/03/08 15:42:18,NaN,NaN,P_Neutral,NaN,NaN,NaN,NaN
98,299,"Zaradi navedenega se področje ureja tako, da s...",2023/03/08 15:29:59,NaN,"""mogoci samo"" implies negative sentiment, neut...",N_Neutral,2023/03/08 15:35:00,NaN,Statment with no direct opinion,P_Neutral,2023/03/08 15:43:10,NaN,NaN,Negative,NaN,NaN,NaN,NaN
99,300,Delničarja mora uprava KAD-a pisno obveščati o...,2023/03/08 15:30:19,NaN,neutral statement. nothing inherently negative.,P_Neutral,2023/03/08 15:35:02,NaN,Statment with no direct opinion,P_Neutral,2023/03/08 15:43:37,NaN,NaN,P_Neutral,NaN,NaN,NaN,NaN

In [13]:
df1 = df.drop(['timestamp_tamara', 'timestamp_anze', 'timestamp_katja', 'rev_tamara', 'rev_anze', 'rev_katja', 'final_tag'], axis = 1)
df1.head()

,id,text,flagged_tamara,comment_tamara,tag_tamara,flagged_anze,comment_anze,tag_anze,flagged_katja,comment_katja,tag_katja
0,201,"In to je, kot sem rekel, tisto, kar bo tudi v ...",NaN,"Opinion is implied, positive sentiment.",Positive,NaN,Speaker opinion. It's on positiv side because ...,P_Neutral,NaN,"Kot sem rekel - speakers opinion, so positive",Positive
1,202,"Slednje se odraža tudi v sami vsebini, ki je p...",NaN,"Implied opinion, negative sentiment.",Negative,NaN,"The statment is negativ, but it's neutral beca...",N_Neutral,NaN,NaN,N_Neutral
2,203,Krščanski demokrati smo dolžni opozoriti na po...,NaN,"Negative theme, negative sentiment ""zavajanje,...",Negative,NaN,Negativ statment and negativ sentiment of the ...,Negative,NaN,We (KS) - implied speakers opinion,Negative
3,204,Prav preko vikenda je bila slovenska javnost š...,NaN,Maybe sarcasm,N_Neutral,NaN,The sentens is not direct opinion of the perso...,N_Neutral,NaN,No implied speakers opinion but negative senti...,N_Neutral
4,205,"Preprosto zaradi tega, ker je že danes država ...",True,"Although there is no specific negative words, ...",N_Neutral,NaN,NaN,Negative,NaN,"Statement without implied speakers opinion, wi...",P_Neutral

In [14]:
from sklearn.metrics import cohen_kappa_score

annotator1 = df1['tag_tamara']
annotator2 = df1['tag_katja']
annotator3 = df1['tag_anze']


cohen_kappa_score(annotator1, annotator2)#Tamara-Katja

0.4994588744588745

In [15]:
cohen_kappa_score(annotator2, annotator3)#Katja - Anže

0.5373520206830862

In [16]:
cohen_kappa_score(annotator1, annotator3)#Tamara-Anže

0.38870431893687707

In [17]:
annotator1 = df1['tag_tamara']
annotator2 = df1['tag_katja']
annotator3 = df1['tag_anze']


kappa1 = cohen_kappa_score(annotator1, annotator2)#Tamara-Katja
kappa2 = cohen_kappa_score(annotator2, annotator3)#Katja-Anže
kappa3 = cohen_kappa_score(annotator1, annotator3)#Tamara-Anže

In [18]:
Cohen_kappa = (kappa1 + kappa2 + kappa3)/3
Cohen_kappa

0.4751717380262792

In [19]:
df1.loc[(df1['tag_tamara'] == 'N_Neutral')| (df1['tag_tamara'] == 'P_Neutral') ,'sent_tamara'] = 'Neutral'
df1.loc[(df1['tag_tamara'] == 'M_Negative') | (df1['tag_tamara'] == 'Negative'), 'sent_tamara'] = 'Negative'
df1.loc[(df1['tag_tamara'] == 'M_Positive') | (df1['tag_tamara'] == 'Positive'), 'sent_tamara'] = 'Positive'

df1.loc[(df1['tag_katja'] == 'N_Neutral')| (df1['tag_katja'] == 'P_Neutral') ,'sent_katja'] = 'Neutral'
df1.loc[(df1['tag_katja'] == 'M_Negative') | (df1['tag_katja'] == 'Negative'), 'sent_katja'] = 'Negative'
df1.loc[(df1['tag_katja'] == 'M_Positive') | (df1['tag_katja'] == 'Positive'), 'sent_katja'] = 'Positive'

df1.loc[(df1['tag_anze'] == 'N_Neutral')| (df1['tag_anze'] == 'P_Neutral') ,'sent_anze'] = 'Neutral'
df1.loc[(df1['tag_anze'] == 'M_Negative') | (df1['tag_anze'] == 'Negative'), 'sent_anze'] = 'Negative'
df1.loc[(df1['tag_anze'] == 'M_Positive') | (df1['tag_anze'] == 'Positive'), 'sent_anze'] = 'Positive'
df1.head()

,id,text,flagged_tamara,comment_tamara,tag_tamara,flagged_anze,comment_anze,tag_anze,flagged_katja,comment_katja,tag_katja,sent_tamara,sent_katja,sent_anze
0,201,"In to je, kot sem rekel, tisto, kar bo tudi v ...",NaN,"Opinion is implied, positive sentiment.",Positive,NaN,Speaker opinion. It's on positiv side because ...,P_Neutral,NaN,"Kot sem rekel - speakers opinion, so positive",Positive,Positive,Positive,Neutral
1,202,"Slednje se odraža tudi v sami vsebini, ki je p...",NaN,"Implied opinion, negative sentiment.",Negative,NaN,"The statment is negativ, but it's neutral beca...",N_Neutral,NaN,NaN,N_Neutral,Negative,Neutral,Neutral
2,203,Krščanski demokrati smo dolžni opozoriti na po...,NaN,"Negative theme, negative sentiment ""zavajanje,...",Negative,NaN,Negativ statment and negativ sentiment of the ...,Negative,NaN,We (KS) - implied speakers opinion,Negative,Negative,Negative,Negative
3,204,Prav preko vikenda je bila slovenska javnost š...,NaN,Maybe sarcasm,N_Neutral,NaN,The sentens is not direct opinion of the perso...,N_Neutral,NaN,No implied speakers opinion but negative senti...,N_Neutral,Neutral,Neutral,Neutral
4,205,"Preprosto zaradi tega, ker je že danes država ...",True,"Although there is no specific negative words, ...",N_Neutral,NaN,NaN,Negative,NaN,"Statement without implied speakers opinion, wi...",P_Neutral,Neutral,Neutral,Negative

In [22]:
sent1 = df1['sent_tamara']
sent2 = df1['sent_katja']
sent3 = df1['sent_anze']

cohen_kappa_score(sent1, sent2)#Tamara-Katja

0.5680345572354212

In [23]:
cohen_kappa_score(sent2, sent3)#Anže - Katja

0.5166747220879653

In [24]:
cohen_kappa_score(sent1, sent3)#Tamara-Anže

0.41747572815533984

In [25]:
sent1 = df1['sent_tamara']
sent2 = df1['sent_katja']
sent3 = df1['sent_anze']

sent_kappa1 =  cohen_kappa_score(sent1, sent2)#Tamara-Katja
sent_kappa2 = cohen_kappa_score(sent2, sent3)#Katja-Anže
sent_kappa3 = cohen_kappa_score(sent1, sent3)#Tamara-Anže

sent_kappa3

0.41747572815533984

In [26]:
Cohen_kappa_sent = (sent_kappa1 + sent_kappa2 + sent_kappa3)/3
Cohen_kappa_sent

0.5007283358262421