In [19]:
import pandas as pd
import csv

In [20]:
df = pd.read_csv("Main3_combined.csv", delimiter = ',', encoding='utf-8')

In [21]:
df.head()

,ID,text,tag_tamara,tag_katja,comments_tamara,comments_katja,flagged_tamara,flagged_katja,chair,final_tag
0,ParlaMint-SI_2013-03-04-SDZ6-Redna-11.u10,"Spoštovani predsednik Vlade, spoštovana minist...",Negative,Negative,"Based on the first part, in connection with th...",While the tone is not especially strong as wit...,NaN,NaN,False,NaN
1,ParlaMint-SI_2017-03-21-SDZ7-Redna-28.u162,Dragi poslanke in poslanci! Danes ne bomo govo...,Negative,Negative,"Negative theme, negative sentiment, dissapoint...",First part explaining why the current state is...,NaN,NaN,False,NaN
2,ParlaMint-SI_2010-11-16-SDZ5-Izredna-33.u1,Spoštovane kolegice poslanke in kolegi poslanc...,P_Neutral,P_Neutral,Procedural,NaN,NaN,NaN,True,NaN
3,ParlaMint-SI_2010-01-28-SDZ5-Redna-13.u172,"Hvala lepa za besedo, gospod podpredsednik. Sp...",M_Positive,M_Negative,"A little diss to the goverment, but overall po...",The very first two sentences seem supportive a...,NaN,1.0,False,NaN
4,ParlaMint-SI_2021-09-21-SDZ8-Redna-25.u92,"Hvala za besedo, gospa podpredsednica. Gospe p...",M_Negative,M_Negative,"Very conflicting, but the sentiment is mostly ...","Negative topic, but the speaker and their PS s...",NaN,1.0,False,NaN

# 6-level schema analysis (Cohen's Kappa (κ))

In [22]:
from sklearn.metrics import cohen_kappa_score
annotator1 = df['tag_tamara']
annotator2 = df['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.7530956567281434)

# κ for non-procedural and procedural speech

In [23]:
df_non = df[df['chair'] != True]

In [24]:
df_procedural = df[df['chair'] == True]

In [25]:
#df_procedural

In [26]:
annotator1 = df_non['tag_tamara']
annotator2 = df_non['tag_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.6114819759679573)

In [27]:
annotator1_procedural = df_procedural['tag_tamara']
annotator2_procedural = df_procedural['tag_katja']
cohen_kappa_score(annotator1_procedural, annotator2_procedural)

np.float64(0.6296444266879744)

# 3-level analysis (Cohen's Kappa (κ))

In [28]:
df.loc[(df['tag_tamara'] == 'Negative') | (df['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df.loc[(df['tag_tamara'] == 'Positive') | (df['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df.loc[(df['tag_tamara'] == 'P_Neutral') | (df['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

In [29]:
df.loc[(df['tag_katja'] == 'Negative') | (df['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df.loc[(df['tag_katja'] == 'Positive') | (df['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df.loc[(df['tag_katja'] == 'P_Neutral') | (df['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

In [30]:
#df

In [31]:
annotator1 = df['sent_tamara']
annotator2 = df['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.8858647936786654)

In [32]:
df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'
df_non.loc[(df_non['tag_tamara'] == 'Positive') | (df_non['tag_tamara'] == 'M_Positive'), 'sent_tamara'] = 'Positive'
df_non.loc[(df_non['tag_tamara'] == 'P_Neutral') | (df_non['tag_tamara'] == 'N_Neutral'), 'sent_tamara'] = 'Neutral'

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_14772/136232902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tag_tamara'] == 'Negative') | (df_non['tag_tamara'] == 'M_Negative'), 'sent_tamara'] = 'Negative'

In [33]:
df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'
df_non.loc[(df_non['tag_katja'] == 'Positive') | (df_non['tag_katja'] == 'M_Positive'), 'sent_katja'] = 'Positive'
df_non.loc[(df_non['tag_katja'] == 'P_Neutral') | (df_non['tag_katja'] == 'N_Neutral'), 'sent_katja'] = 'Neutral'

/var/folders/ng/b52w03cd2d31sdjpmc5kyqlh0000gr/T/ipykernel_14772/4240778448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non.loc[(df_non['tag_katja'] == 'Negative') | (df_non['tag_katja'] == 'M_Negative'), 'sent_katja'] = 'Negative'

In [34]:
annotator1 = df_non['sent_tamara']
annotator2 = df_non['sent_katja']
cohen_kappa_score(annotator1, annotator2)

np.float64(0.8067729083665338)

# Generating dataset for consolidation

Adding new column for the final annotation, provided with consolidation

Note: Comment out after consolidation dataset is created

In [35]:
df['final_tag'] = df.apply(lambda row: row['tag_tamara'] if row['tag_tamara'] == row['tag_katja'] else None, axis=1)
df.to_csv("Main3_consolidation.csv", encoding = 'utf-8')

# Aggergating Kappa scores

In [36]:
kappa_scores = {
    "6-level":{
        "full":0.75,
        "non-procedural":0.61
        
    },
    "3-level":{
        "full": 0.89,
        "non-procedural":0.81
    }
}

df_kappa = pd.DataFrame(kappa_scores)

def create_test_df(kappa_scores, test_label):
    df_kappa = pd.DataFrame(kappa_scores).reset_index()
    df_kappa.rename(columns={'index': 'Type'}, inplace=True)
    df_kappa['Phase'] = test_label
    # Reorder columns to place 'Test' before 'Type'
    df_kappa = df_kappa[['Phase', 'Type', '6-level', '3-level']]
    return df_kappa

In [37]:
df_test = create_test_df(kappa_scores, 'Main3')
df_test

   Phase            Type  6-level  3-level
0  Main3            full     0.75     0.89
1  Main3  non-procedural     0.61     0.81

In [38]:
df_test.to_csv("../Kappa_scores_Main3.csv", index=False)