In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv('../../Datasets/Sentiment_Analysis/CHES-SI.tsv', delimiter='\t', encoding='utf-8')
df

,country,pm_id,ches_id,year,chesversion,lrgen,lrecon,lrecon_blur,lrecon_dissent,lrecon_salience,...,seat,social_salience,sociallifestyle,spendvtax,spendvtax_salience,urban_rural,urban_salience,us,us_salience,vote
0,SI,DL,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
1,SI,DLGV,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
2,SI,DeSUS,DeSUS,2002,2020.1,3.4,3.4,-,-,-,...,4.40,-,-,-,-,-,-,-,-,5.2
3,SI,DeSUS,DeSUS,2006,2020.1,3.2,2.6,-,-,-,...,4.40,4.60,4.40,2.80,5.60,5.20,3.60,3.8,3.8,4
4,SI,DeSUS,DeSUS,2010,2020.1,4.25,3.33,-,-,-,...,7.80,3.25,5.17,2.40,7.20,4.91,3.73,-,-,7.5
5,SI,DeSUS,DeSUS,2014,2020.1,4.15,4.0,-,-,5.54,...,11.1,-,5.10,3.36,-,5.22,-,-,-,10.2
6,SI,DeSUS,DeSUS,2019,2020.1,3.77,3.29,4.71,2.57,4.67,...,5.70,-,4.29,2.53,-,4.93,-,-,-,4.93
7,SI,GAS,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
8,SI,Konkretno,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9,SI,LDS,LDS,2002,2020.1,4.2,6.2,-,-,-,...,37.80,-,-,-,-,-,-,-,-,36.3
10,SI,LDS,LDS,2006,2020.1,3.4,3.8,-,-,-,...,25.6,7.60,2,4.20,6.20,2.80,3.80,4.60,4.20,22.8
11,SI,LDS,LDS,2010,2020.1,4.75,5.83,-,-,-,...,5.60,7.17,1,5.90,5.20,2.17,3.91,-,-,5.21
12,SI,LMŠ,LMS,2019,2020.1,4.36,4.64,5.43,3.67,6.13,...,14.8,-,3.64,4.20,-,4.87,-,-,-,12.6
13,SI,Levica,ZL,2014,2020.1,1.0,0.67,-,-,6.62,...,6.70,-,1.17,1.90,-,2.89,-,-,-,6
14,SI,Levica,Levica,2019,2020.1,0.71,0.71,1.57,1.71,5.93,...,10.2,-,.5,1.53,-,1.93,-,-,-,9.33
15,SI,Lipa,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
16,SI,NP,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
17,SI,NSi,NSI,2002,2020.1,7.0,4.8,-,-,-,...,8.90,-,-,-,-,-,-,-,-,8.6
18,SI,NSi,NSI,2006,2020.1,8.4,6.8,-,-,-,...,10,5.60,8.40,6.80,4.60,5.40,6,6,4.60,9
19,SI,NSi,NSI,2010,2020.1,7.82,6.33,-,-,-,...,0,8.25,9.17,5.38,5.62,7.91,7.45,-,-,3.4
20,SI,NSi,NSI,2014,2020.1,7.85,8.08,-,-,6.85,...,5.60,-,8.92,7.82,-,8,-,-,-,5.6
21,SI,NSi,NSI,2019,2020.1,7.5,7.36,2.57,1.86,7.33,...,8,-,8.07,7.47,-,7.13,-,-,-,7.16
22,SI,NeP,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
23,SI,PS,PS,2014,2020.1,3.38,4.15,-,-,6.69,...,0,-,3.58,4.80,-,3.22,-,-,-,3
24,SI,SAB,AB,2019,2020.1,4.21,4.36,5,2.57,6,...,5.70,-,2.79,4.07,-,3.93,-,-,-,5.11
25,SI,SD,ZLSD,2002,2020.1,3.6,4.2,-,-,-,...,12.2,-,-,-,-,-,-,-,-,12.1
26,SI,SD,ZLSD,2006,2020.1,3.6,3.4,-,-,-,...,11.1,7,2.60,3.20,6.80,3.60,4.60,4.80,4.60,10.2
27,SI,SD,SD,2010,2020.1,3.67,3.75,-,-,-,...,32.20,5,2.33,3.10,6.90,2.75,3.42,-,-,30.5
28,SI,SD,SD,2014,2020.1,3.15,3.42,-,-,6.15,...,6.70,-,2.75,3.18,-,4.11,-,-,-,6
29,SI,SD,SD,2019,2020.1,2.57,3.07,3.29,2,6.07,...,11.4,-,1.57,2.67,-,3.67,-,-,-,9.93
30,SI,SDS,SDS,2002,2020.1,6.4,4.8,-,-,-,...,15.6,-,-,-,-,-,-,-,-,15.8
31,SI,SDS,SDS,2006,2020.1,7.4,6.4,-,-,-,...,32.20,5.20,6.80,5.60,5.40,5,4.20,7,6,29.1
32,SI,SDS,SDS,2010,2020.1,6.92,5.92,-,-,-,...,31.1,5.67,7,5.64,5.80,6,5.5,-,-,29.3
33,SI,SDS,SDS,2014,2020.1,8.69,8.62,-,-,6.08,...,23.30,-,8.5,7.91,-,7.12,-,-,-,20.7
34,SI,SDS,SDS,2019,2020.1,8.64,7.5,2.43,1.29,7.47,...,28.4,-,8.43,7.73,-,6.73,-,-,-,24.92
35,SI,SKD,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
36,SI,SLS,SLS,2006,2020.1,6.4,5.0,-,-,-,...,7.80,5.20,7.20,4.20,4.60,7.20,8,4.80,3.8,6.8
37,SI,SLS,SLS,2014,2020.1,6.46,6.31,-,-,5.77,...,0,-,7.25,6.10,-,8.22,-,-,-,4
38,SI,SLS+SKD,SLS-SKD,2002,2020.1,6.8,5.0,-,-,-,...,10,-,-,-,-,-,-,-,-,9.6
39,SI,SMC,SMC,2014,2020.1,5.25,5.38,-,-,6.38,...,40,-,4.67,5,-,4.22,-,-,-,34.5
40,SI,SMC,SMC,2019,2020.1,4.79,5.14,4.86,3.71,6.33,...,11.4,-,3.5,4.80,-,3.40,-,-,-,9.75
41,SI,SMS,SMS,2002,2020.1,4.4,4.0,-,-,-,...,4.40,-,-,-,-,-,-,-,-,4.3
42,SI,SNS,SNS,2002,2020.1,3.6,4.2,-,-,-,...,4.40,-,-,-,-,-,-,-,-,4.4
43,SI,SNS,SNS,2006,2020.1,6.0,4.2,-,-,-,...,6.70,7.40,8.60,4.20,4,5.20,3.80,3,5.20,6.3
44,SI,SNS,SNS,2010,2020.1,8.0,6.0,-,-,-,...,5.60,7.5,9.25,6.12,3.44,5,3.67,-,-,5.4
45,SI,SNS,SNS,2019,2020.1,8.71,6.31,6.33,1.57,4.07,...,4.5,-,8.85,6.5,-,5.71,-,-,-,4.17
46,SI,ZL,ZL,2014,2020.1,1.0,0.67,-,-,6.62,...,6.70,-,1.17,1.90,-,2.89,-,-,-,6
47,SI,ZLSD,ZLSD,2002,2020.1,3.6,4.2,-,-,-,...,12.2,-,-,-,-,-,-,-,-,12.1
48,SI,ZLSD,ZLSD,2006,2020.1,3.6,3.4,-,-,-,...,11.1,7,2.60,3.20,6.80,3.60,4.60,4.80,4.60,10.2
49,SI,ZaAB,ZaAB,2014,2020.1,4.15,4.69,-,-,7,...,4.40,-,3.20,5.5,-,3.56,-,-,-,4.4
50,SI,ZaSLD,AB,2019,2020.1,4.21,4.36,5,2.57,6,...,5.70,-,2.79,4.07,-,3.93,-,-,-,5.11
51,SI,Zares,Zares,2010,2020.1,3.92,4.58,-,-,-,...,10,6.83,0.92,4.60,6.20,2.25,3.67,-,-,9.4

In [8]:
#Convert CHES scores to interger
exclude = ['country', 'pm_id', 'ches_id', 'chesversion']
df[df.columns.difference(exclude)] = df[df.columns.difference(exclude)].apply(pd.to_numeric, errors='coerce')
df.head()

,country,pm_id,ches_id,year,chesversion,lrgen,lrecon,lrecon_blur,lrecon_dissent,lrecon_salience,...,seat,social_salience,sociallifestyle,spendvtax,spendvtax_salience,urban_rural,urban_salience,us,us_salience,vote
0,SI,DL,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SI,DLGV,-,NaN,-,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SI,DeSUS,DeSUS,2002.0,2020.1,3.40,3.40,NaN,NaN,NaN,...,4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.2
3,SI,DeSUS,DeSUS,2006.0,2020.1,3.20,2.60,NaN,NaN,NaN,...,4.4,4.60,4.40,2.8,5.6,5.20,3.60,3.8,3.8,4.0
4,SI,DeSUS,DeSUS,2010.0,2020.1,4.25,3.33,NaN,NaN,NaN,...,7.8,3.25,5.17,2.4,7.2,4.91,3.73,NaN,NaN,7.5

## LRGEN Scores by Party across Years

In [40]:
lrgen = df.groupby(['pm_id', 'year'])[['lrgen']].mean().reset_index()
lrgen['year'] = lrgen['year'].astype(int)
lrgen.head()

   pm_id  year  lrgen
0  DeSUS  2002   3.40
1  DeSUS  2006   3.20
2  DeSUS  2010   4.25
3  DeSUS  2014   4.15
4  DeSUS  2019   3.77

In [41]:
fig = px.line(lrgen, x='year', y='lrgen', color='pm_id', 
              markers=True, title='LRGEN Scores by Parties Across Years',
              labels={'year': 'Year', 'lrgen': 'CIVLIB Score', 'pm_id': 'Party'})

# Improve layout
fig.update_layout(
    xaxis=dict(tickmode='linear', dtick=3),  # Step of 3 for x-axis ticks
    yaxis_title='LRGEN Score',
    legend_title='Party',
    template='plotly_white'
)

## LRECON Scores by Party across Years

In [42]:
lrecon = df.groupby(['pm_id', 'year'])[['lrecon']].mean().reset_index()
lrecon['year'] = lrecon['year'].astype(int)
lrecon.head()

   pm_id  year  lrecon
0  DeSUS  2002    3.40
1  DeSUS  2006    2.60
2  DeSUS  2010    3.33
3  DeSUS  2014    4.00
4  DeSUS  2019    3.29

In [44]:
fig = px.line(lrecon, x='year', y='lrecon', color='pm_id', 
              markers=True, title='LRECON Scores by Parties Across Years',
              labels={'year': 'Year', 'lrecon': 'LRECON Score', 'pm_id': 'Party'})

# Improve layout
fig.update_layout(
    xaxis=dict(tickmode='linear', dtick=3),  # Step of 3 for x-axis ticks
    yaxis_title='LRECON Score',
    legend_title='Party',
    template='plotly_white'
)

## Redistribution Scores by Party across Years

In [25]:
redistribution = df.groupby(['pm_id', 'year'])[['redistribution']].mean().reset_index()
redistribution['year'] = redistribution['year'].astype(int)
redistribution.head()

   pm_id  year  redistribution
0  DeSUS  2002             NaN
1  DeSUS  2006            3.00
2  DeSUS  2010            3.58
3  DeSUS  2014            4.56
4  DeSUS  2019            2.79

In [33]:
fig = px.line(redistribution, x='year', y='redistribution', color='pm_id', 
              markers=True, title='Redistribution Scores by Parties Across Years',
              labels={'year': 'Year', 'redistribution': 'LRGEN Score', 'pm_id': 'Party'})

# Improve layout
fig.update_layout(
    xaxis=dict(tickmode='linear', dtick=3),  # Step of 3 for x-axis ticks
    yaxis_title='Redistribution Score',
    legend_title='Party',
    template='plotly_white'
)

## CIVLIB Scores by Party across Years

In [37]:
civlib = df.groupby(['pm_id', 'year'])[['civlib_laworder']].mean().reset_index()
civlib['year'] = civlib['year'].astype(int)
civlib.head()

   pm_id  year  civlib_laworder
0  DeSUS  2002              NaN
1  DeSUS  2006             4.80
2  DeSUS  2010             5.73
3  DeSUS  2014             5.30
4  DeSUS  2019             4.00

In [39]:
fig = px.line(civlib, x='year', y='civlib_laworder', color='pm_id', 
              markers=True, title='CIVLIB Scores by Parties Across Years',
              labels={'year': 'Year', 'civlib_laworder': 'CIVLIB Score', 'pm_id': 'Party'})

# Improve layout
fig.update_layout(
    xaxis=dict(tickmode='linear', dtick=3),  # Step of 3 for x-axis ticks
    yaxis_title='CIVLIB Score',
    legend_title='Party',
    template='plotly_white'
)